const $=s=>document.querySelector(s); const uid=()=>Math.random().toString(36).slice(2,9); const money=n=>'S/ '+(Number(n)||0).toFixed(2);
const MODES={GENERAL:'Actividades generales → varios equipos',PROPIAS:'Cada equipo con sus propias actividades',REPUESTOS:'Venta de repuestos / accesorios'};
const emptyState={
 empresas:[{id:'emp1',nombre:'SERVITEC BIOMEDICAL',ruc:'20600000001',telefono:'999 999 999',correo:'ventas@servitec.pe',logo:''}],
 clientes:[{id:'cli1',nombre:'Hospital Regional Demo',ruc:'-',establecimientos:[{id:'est1',nombre:'Sede Principal',areas:[{id:'ar1',nombre:'Odontología'},{id:'ar2',nombre:'Centro quirúrgico'}]}]}],
 cotizaciones:[], ejecuciones:[], inventario:[]
};
let state=loadLocal(); let tab='Dashboard'; let editingQuote=null; let quoteDraft=null; let cloud='Modo local'; let saveTimer=null;
const env=window.SERVITEC_ENV||{}; const hasCloud=!!(env.SUPABASE_URL&&env.SUPABASE_KEY);
function clone(o){return JSON.parse(JSON.stringify(o))} function loadLocal(){try{return {...emptyState,...JSON.parse(localStorage.getItem('servitec_v138')||'{}')}}catch{return clone(emptyState)}}
function persist(){localStorage.setItem('servitec_v138',JSON.stringify(state)); if(hasCloud){clearTimeout(saveTimer); saveTimer=setTimeout(saveCloud,450)}}
async function loadCloud(){if(!hasCloud){cloud='Modo local: falta VITE_SUPABASE_KEY';render();return} cloud='Conectando Supabase...';render(); try{let r=await fetch(`${env.SUPABASE_URL}/rest/v1/app_state?id=eq.global&select=payload`,{headers:{apikey:env.SUPABASE_KEY,Authorization:`Bearer ${env.SUPABASE_KEY}`}}); let data=await r.json(); if(Array.isArray(data)&&data[0]?.payload){state={...emptyState,...data[0].payload}; localStorage.setItem('servitec_v138',JSON.stringify(state));} cloud='Nube Supabase activa';render()}catch(e){cloud='Modo local: Supabase no respondió';render()}}
async function saveCloud(){try{await fetch(`${env.SUPABASE_URL}/rest/v1/app_state`,{method:'POST',headers:{apikey:env.SUPABASE_KEY,Authorization:`Bearer ${env.SUPABASE_KEY}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'global',payload:state,updated_at:new Date().toISOString()})});cloud='Nube Supabase activa'}catch(e){cloud='Modo local: error al sincronizar'}renderHeaderOnly()}
function setState(fn){state=typeof fn==='function'?fn(state):fn; persist(); render()}
function renderHeaderOnly(){const t=$('.tag'); if(t)t.textContent=cloud}
function render(){document.getElementById('app').innerHTML=`<header class="top"><div><h1>SERVITEC PRO V13.8 RESCATE REAL</h1><b>Cotización dinámica + Nube + PDFs corporativos</b></div><div class="tag">${cloud}</div></header><nav class="nav">${['Dashboard','Empresas','Clientes','Cotizaciones','Ejecución','Actas','Informes','Inventario','Configuración'].map(x=>`<button class="${tab===x?'active':''}" data-tab="${x}">${x}</button>`).join('')}</nav><main>${view()}</main>`; document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;editingQuote=null;quoteDraft=null;render()}); bind();}
function backBtn(){return `<button class="btn primary" data-action="back">← Atrás</button>`}
function view(){return ({Dashboard:viewDashboard,Empresas:viewEmpresas,Clientes:viewClientes,Cotizaciones:viewCotizaciones,Ejecución:viewEjecucion,Actas:()=>viewDocs('acta'),Informes:()=>viewDocs('informe'),Inventario:viewInventario,Configuración:viewConfig}[tab]||viewDashboard)()}
function bind(){document.querySelectorAll('[data-action="back"]').forEach(b=>b.onclick=()=>{editingQuote=null;quoteDraft=null;tab='Dashboard';render()}); const map={saveEmpresa,saveCliente,saveEst,saveArea,newQuote,saveQuote,addEquipoGeneral,addEquipoPropio,addActGeneral,importActGeneral,addActToEquipo,importActToEquipo,addRepuesto,importRepuestos,deleteSelectedActs,deleteQuote,editQuote,printQuote,exportCsv,exportWord,saveInv,printDoc}; document.querySelectorAll('[data-action]').forEach(el=>{const fn=map[el.dataset.action]; if(fn) el.onclick=()=>fn(el)}); document.querySelectorAll('[data-bind]').forEach(el=>{el.oninput=el.onchange=()=>updateDraft(el.dataset.bind,el.value,el.dataset.id)});}
function viewDashboard(){return `<section class="wrap"><h2>Dashboard</h2><div class="grid"><div class="card"><b>Empresas</b><h1>${state.empresas.length}</h1></div><div class="card"><b>Clientes</b><h1>${state.clientes.length}</h1></div><div class="card"><b>Cotizaciones</b><h1>${state.cotizaciones.length}</h1></div><div class="card"><b>Inventario</b><h1>${state.inventario.length}</h1></div></div><p class="notice">Si ves “V13.8 RESCATE REAL”, ya estás en la versión correcta. Esta versión no usa React ni Vite en runtime: es estable para Vercel.</p></section>`}
function viewEmpresas(){return `<section class="wrap">${backBtn()}<h2>Empresas</h2><div class="grid"><input id="empNom" placeholder="Razón social"><input id="empRuc" placeholder="RUC"><input id="empTel" placeholder="Teléfono"><input id="empCor" placeholder="Correo"></div><br><button class="btn green" data-action="saveEmpresa">+ Nueva empresa</button><div class="desktopWide"><table class="table"><thead><tr><th>Empresa</th><th>RUC</th><th>Contacto</th></tr></thead><tbody>${state.empresas.map(e=>`<tr><td>${e.nombre}</td><td>${e.ruc||''}</td><td>${e.telefono||''} · ${e.correo||''}</td></tr>`).join('')}</tbody></table></div></section>`}
function saveEmpresa(){let nombre=$('#empNom').value.trim(); if(!nombre)return; state.empresas.push({id:uid(),nombre,ruc:$('#empRuc').value,telefono:$('#empTel').value,correo:$('#empCor').value});persist();render()}
function viewClientes(){let selected=state.clientes[0]; return `<section class="wrap">${backBtn()}<h2>Clientes</h2><div class="grid2"><input id="cliNom" placeholder="Nombre cliente"><input id="cliRuc" placeholder="RUC"></div><br><button class="btn primary" data-action="saveCliente">+ Nuevo cliente</button><hr><div class="grid2"><select id="cliSel">${state.clientes.map(c=>`<option value="${c.id}">${c.nombre}</option>`).join('')}</select><input id="estNom" placeholder="Nuevo establecimiento"></div><br><button class="btn green" data-action="saveEst">Agregar establecimiento</button>${selected?`<div class="card"><h3>${selected.nombre}</h3>${selected.establecimientos.map(es=>`<div class="card"><b>${es.nombre}</b><ul>${es.areas.map(a=>`<li>${a.nombre}</li>`).join('')}</ul><div class="row"><input id="area_${es.id}" placeholder="Nueva área usuaria"><button class="btn" data-action="saveArea" data-id="${es.id}">Agregar área</button></div></div>`).join('')}</div>`:''}</section>`}
function saveCliente(){let nombre=$('#cliNom').value.trim(); if(!nombre)return; state.clientes.push({id:uid(),nombre,ruc:$('#cliRuc').value,establecimientos:[]});persist();render()}
function saveEst(){let cid=$('#cliSel').value, nombre=$('#estNom').value.trim(); if(!nombre)return; state.clientes=state.clientes.map(c=>c.id===cid?{...c,establecimientos:[...c.establecimientos,{id:uid(),nombre,areas:[]}]}:c);persist();render()}
function saveArea(el){let eid=el.dataset.id, nombre=$(`#area_${eid}`).value.trim(); if(!nombre)return; state.clientes=state.clientes.map(c=>({...c,establecimientos:c.establecimientos.map(e=>e.id===eid?{...e,areas:[...e.areas,{id:uid(),nombre}]}:e)}));persist();render()}
function initDraft(q){if(q)return clone(q); const c=state.clientes[0]||{}; const e=c.establecimientos?.[0]||{}; const a=e.areas?.[0]||{}; return {id:uid(),numero:`COT-${new Date().getFullYear()}-${String(state.cotizaciones.length+1).padStart(4,'0')}`,empresaId:state.empresas[0]?.id||'',clienteId:c.id||'',estId:e.id||'',areaId:a.id||'',tipo:'Mantenimiento preventivo',config:MODES.GENERAL,equipos:[],acts:[],repuestos:[],total:0,fecha:new Date().toISOString()}}
function viewCotizaciones(){if(quoteDraft)return viewQuoteForm(); return `<section class="wrap">${backBtn()}<h2>Cotizaciones</h2><button class="btn primary" data-action="newQuote">+ Nueva cotización</button><div class="desktopWide"><table class="table"><thead><tr><th>N°</th><th>Cliente</th><th>Configuración</th><th>Total</th><th>Acciones</th></tr></thead><tbody>${state.cotizaciones.map(q=>`<tr><td>${q.numero}</td><td>${q.clienteNombre||''}</td><td>${q.config}</td><td>${money(q.total)}</td><td class="actions"><button class="btn" data-action="editQuote" data-id="${q.id}">Editar</button><button class="btn green" data-action="printQuote" data-id="${q.id}">PDF</button><button class="btn" data-action="exportCsv" data-id="${q.id}">Excel</button><button class="btn" data-action="exportWord" data-id="${q.id}">Word</button><button class="btn danger" data-action="deleteQuote" data-id="${q.id}">Eliminar</button></td></tr>`).join('')}</tbody></table></div></section>`}
function newQuote(){quoteDraft=initDraft(); render()} function editQuote(el){quoteDraft=initDraft(state.cotizaciones.find(q=>q.id===el.dataset.id)); render()} function deleteQuote(el){if(confirm('¿Eliminar cotización?'))setState(s=>({...s,cotizaciones:s.cotizaciones.filter(q=>q.id!==el.dataset.id)}))}
function clientData(){let c=state.clientes.find(x=>x.id===quoteDraft.clienteId)||state.clientes[0]||{}; let ests=c.establecimientos||[]; let e=ests.find(x=>x.id===quoteDraft.estId)||ests[0]||{}; let areas=e.areas||[]; let a=areas.find(x=>x.id===quoteDraft.areaId)||areas[0]||{}; return {c,ests,e,areas,a}}
function calcTotal(q=quoteDraft){if(q.config===MODES.REPUESTOS)return q.repuestos.reduce((s,r)=>s+(+r.cantidad||0)*(+r.precio||0),0); if(q.config===MODES.PROPIAS)return q.equipos.reduce((s,e)=>s+(e.acts||[]).reduce((a,x)=>a+(+x.cantidad||0)*(+x.precio||0),0),0); return q.acts.reduce((s,a)=>s+(+a.cantidad||0)*(+a.precio||0),0)}
function viewQuoteForm(){let {c,ests,e,areas}=clientData(); quoteDraft.total=calcTotal(); return `<section class="wrap">${backBtn()}<h2>Nueva cotización</h2><div class="grid"><select data-bind="clienteId">${state.clientes.map(x=>`<option value="${x.id}" ${x.id===quoteDraft.clienteId?'selected':''}>${x.nombre}</option>`).join('')}</select><select data-bind="estId">${ests.map(x=>`<option value="${x.id}" ${x.id===quoteDraft.estId?'selected':''}>${x.nombre}</option>`).join('')}</select><select data-bind="areaId">${areas.map(x=>`<option value="${x.id}" ${x.id===quoteDraft.areaId?'selected':''}>${x.nombre}</option>`).join('')}</select><select data-bind="tipo">${['Mantenimiento preventivo','Mantenimiento correctivo','Calibración','Servicio + repuestos','Venta'].map(x=>`<option ${x===quoteDraft.tipo?'selected':''}>${x}</option>`).join('')}</select><select data-bind="config">${Object.values(MODES).map(x=>`<option ${x===quoteDraft.config?'selected':''}>${x}</option>`).join('')}</select></div><div class="bar"><b>Modo activo:</b> ${quoteDraft.config}<span class="total">Total: ${money(quoteDraft.total)}</span></div>${quoteModeView()}<div class="bar"><button class="btn green" data-action="saveQuote">Guardar y volver a lista</button><button class="btn danger" onclick="location.reload()">Cancelar</button></div></section>`}
function updateDraft(key,val,id){if(!quoteDraft)return; if(key==='clienteId'){quoteDraft.clienteId=val; let c=state.clientes.find(x=>x.id===val); quoteDraft.estId=c?.establecimientos?.[0]?.id||''; quoteDraft.areaId=c?.establecimientos?.[0]?.areas?.[0]?.id||''; render(); return} if(key==='estId'){quoteDraft.estId=val; let {e}=clientData(); quoteDraft.areaId=e?.areas?.[0]?.id||''; render(); return} if(key==='config'){quoteDraft.config=val; render(); return} quoteDraft[key]=val; render()}
function quoteModeView(){if(quoteDraft.config===MODES.REPUESTOS)return viewRepuestos(); if(quoteDraft.config===MODES.PROPIAS)return viewEquiposPropios(); return viewGeneral()}
function viewGeneral(){return `<p class="notice">Este modo aplica UNA lista de actividades generales a TODOS los equipos registrados.</p><div class="bar"><button class="btn green" data-action="addEquipoGeneral">+ Equipo</button><button class="btn green" data-action="addActGeneral">+ Actividad</button><button class="btn" data-action="importActGeneral">Importar solo descripciones</button></div><h3>Equipos incluidos</h3>${equiposTable(quoteDraft.equipos,'general')}<h3>Actividades generales</h3>${actsTable(quoteDraft.acts,'general')}`}
function viewEquiposPropios(){return `<p class="notice">Este modo crea actividades separadas por cada equipo. No existe tabla general.</p><div class="bar"><button class="btn green" data-action="addEquipoPropio">+ Equipo con actividades propias</button></div>${quoteDraft.equipos.map((eq,i)=>`<div class="card"><h3>Equipo ${i+1}</h3>${equipoFields(eq)}<div class="bar"><button class="btn green" data-action="addActToEquipo" data-id="${eq.id}">+ Actividad para este equipo</button><button class="btn" data-action="importActToEquipo" data-id="${eq.id}">Importar actividades de este equipo</button></div>${actsTable(eq.acts||[],'equipo',eq.id)}</div>`).join('')}`}
function viewRepuestos(){return `<p class="notice">Modo venta: no se muestran equipos. Solo repuestos, accesorios o consumibles.</p><div class="bar"><button class="btn green" data-action="addRepuesto">+ Repuesto / accesorio</button><button class="btn" data-action="importRepuestos">Importar descripciones</button></div><div class="mobileTable"><table class="table"><thead><tr><th>Código</th><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>${quoteDraft.repuestos.map(r=>`<tr><td><input placeholder="Código" value="${esc(r.codigo)}" data-bind="rep_codigo" data-id="${r.id}"></td><td><textarea placeholder="Descripción del repuesto/accesorio" data-bind="rep_descripcion" data-id="${r.id}">${esc(r.descripcion)}</textarea></td><td><input type="number" placeholder="1" value="${r.cantidad}" data-bind="rep_cantidad" data-id="${r.id}"></td><td><input type="number" placeholder="0" value="${r.precio}" data-bind="rep_precio" data-id="${r.id}"></td><td>${money((+r.cantidad||0)*(+r.precio||0))}</td></tr>`).join('')}</tbody></table></div>`}
function equipoFields(eq){return `<div class="grid"><input placeholder="Nombre del equipo" value="${esc(eq.nombre)}" data-bind="eq_nombre" data-id="${eq.id}"><input placeholder="Marca" value="${esc(eq.marca)}" data-bind="eq_marca" data-id="${eq.id}"><input placeholder="Modelo" value="${esc(eq.modelo)}" data-bind="eq_modelo" data-id="${eq.id}"><input placeholder="Serie" value="${esc(eq.serie)}" data-bind="eq_serie" data-id="${eq.id}"></div>`}
function equiposTable(list){return `<div class="mobileTable"><table class="table"><thead><tr><th>Equipo</th><th>Marca</th><th>Modelo</th><th>Serie</th></tr></thead><tbody>${list.map(eq=>`<tr><td><input placeholder="Equipo biomédico" value="${esc(eq.nombre)}" data-bind="eq_nombre" data-id="${eq.id}"></td><td><input placeholder="Marca" value="${esc(eq.marca)}" data-bind="eq_marca" data-id="${eq.id}"></td><td><input placeholder="Modelo" value="${esc(eq.modelo)}" data-bind="eq_modelo" data-id="${eq.id}"></td><td><input placeholder="Serie" value="${esc(eq.serie)}" data-bind="eq_serie" data-id="${eq.id}"></td></tr>`).join('')}</tbody></table></div>`}
function actsTable(list,scope,eid=''){return `<div class="mobileTable"><table class="table"><thead><tr><th>Sel.</th><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>${list.map(a=>`<tr><td><input type="checkbox" data-select-act="${a.id}" data-scope="${scope}" data-eid="${eid}"></td><td><textarea placeholder="Descripción de actividad" data-bind="act_descripcion" data-id="${a.id}" data-eid="${eid}">${esc(a.descripcion)}</textarea></td><td><input type="number" placeholder="1" value="${a.cantidad}" data-bind="act_cantidad" data-id="${a.id}" data-eid="${eid}"></td><td><input type="number" placeholder="0" value="${a.precio}" data-bind="act_precio" data-id="${a.id}" data-eid="${eid}"></td><td>${money((+a.cantidad||0)*(+a.precio||0))}</td></tr>`).join('')}</tbody></table></div>`}
function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')}
function addEquipo(){return {id:uid(),nombre:'',marca:'',modelo:'',serie:'',acts:[]}} function addAct(){return {id:uid(),descripcion:'',cantidad:1,precio:0}} function addRep(){return {id:uid(),codigo:'',descripcion:'',cantidad:1,precio:0}}
function addEquipoGeneral(){quoteDraft.equipos.push(addEquipo());render()} function addEquipoPropio(){quoteDraft.equipos.push(addEquipo());render()} function addActGeneral(){quoteDraft.acts.push(addAct());render()} function addActToEquipo(el){let eq=quoteDraft.equipos.find(e=>e.id===el.dataset.id); eq.acts=eq.acts||[]; eq.acts.push(addAct());render()} function addRepuesto(){quoteDraft.repuestos.push(addRep());render()}
function importLines(msg){let raw=prompt(msg+'\nUna descripción por línea. Cantidad queda en 1 y precio en 0.'); return raw?raw.split(/\n+/).map(x=>x.trim()).filter(Boolean):[]} function importActGeneral(){quoteDraft.acts.push(...importLines('Pega actividades generales').map(descripcion=>({...addAct(),descripcion})));render()} function importActToEquipo(el){let eq=quoteDraft.equipos.find(e=>e.id===el.dataset.id); eq.acts=eq.acts||[]; eq.acts.push(...importLines('Pega actividades para este equipo').map(descripcion=>({...addAct(),descripcion})));render()} function importRepuestos(){quoteDraft.repuestos.push(...importLines('Pega repuestos/accesorios').map(descripcion=>({...addRep(),descripcion})));render()}
function updateNested(key,val,id){if(key.startsWith('eq_')){let prop=key.split('_')[1]; quoteDraft.equipos=quoteDraft.equipos.map(e=>e.id===id?{...e,[prop]:val}:e)} else if(key.startsWith('act_')){let prop=key.split('_')[1]; let eid=event.target.dataset.eid; if(eid){quoteDraft.equipos=quoteDraft.equipos.map(eq=>eq.id===eid?{...eq,acts:(eq.acts||[]).map(a=>a.id===id?{...a,[prop]:val}:a)}:eq)} else quoteDraft.acts=quoteDraft.acts.map(a=>a.id===id?{...a,[prop]:val}:a)} else if(key.startsWith('rep_')){let prop=key.split('_')[1]; quoteDraft.repuestos=quoteDraft.repuestos.map(r=>r.id===id?{...r,[prop]:val}:r)} }
const oldUpdate=updateDraft; updateDraft=function(key,val,id){if(['eq','act','rep'].some(p=>key.startsWith(p+'_'))){updateNested(key,val,id);render();return} oldUpdate(key,val,id)}
function saveQuote(){let {c,e,a}=clientData(); quoteDraft.total=calcTotal(); quoteDraft.clienteNombre=c?.nombre||''; quoteDraft.establecimientoNombre=e?.nombre||''; quoteDraft.areaNombre=a?.nombre||''; let exists=state.cotizaciones.some(q=>q.id===quoteDraft.id); state.cotizaciones=exists?state.cotizaciones.map(q=>q.id===quoteDraft.id?clone(quoteDraft):q):[...state.cotizaciones,clone(quoteDraft)]; quoteDraft=null; persist(); render()}
function rows(q){if(q.config===MODES.REPUESTOS)return q.repuestos||[]; if(q.config===MODES.PROPIAS)return (q.equipos||[]).flatMap(e=>(e.acts||[]).map(a=>({...a,descripcion:`${e.nombre||'Equipo'}: ${a.descripcion}`}))); return q.acts||[]}
function findQ(el){return state.cotizaciones.find(q=>q.id===el.dataset.id)} function printQuote(el){printHtml(docHtml(findQ(el),'COTIZACIÓN'))} function printDoc(el){printHtml(docHtml(findQ(el),el.dataset.type==='acta'?'ACTA DE CONFORMIDAD':'INFORME TÉCNICO'))}
function docHtml(q,title){let c=state.empresas.find(e=>e.id===q.empresaId)||state.empresas[0]||{}; return `<html><head><title>${title}</title><style>body{font-family:Arial;margin:34px;color:#001b3f}.head{display:flex;justify-content:space-between;border-bottom:5px solid #0f7f73;padding-bottom:12px}.logo{font-size:30px;font-weight:900;color:#0f7f73}.box{background:#f1f7ff;padding:14px;border-radius:12px;margin:16px 0}table{width:100%;border-collapse:collapse}th{background:#0f7f73;color:#fff}th,td{border:1px solid #d7e4f5;padding:9px}.total{text-align:right;font-size:23px;font-weight:900}.firmas{display:flex;justify-content:space-between;margin-top:70px}.line{border-top:1px solid #001b3f;width:240px;text-align:center;padding-top:8px}</style></head><body><div class="head"><div><div class="logo">${c.nombre||'SERVITEC PRO'}</div><div>RUC ${c.ruc||''} · ${c.telefono||''} · ${c.correo||''}</div></div><h1>${title}</h1></div><div class="box"><b>N°:</b> ${q.numero}<br><b>Cliente:</b> ${q.clienteNombre}<br><b>Establecimiento:</b> ${q.establecimientoNombre}<br><b>Área usuaria:</b> ${q.areaNombre}<br><b>Tipo:</b> ${q.tipo}<br><b>Configuración:</b> ${q.config}</div><table><thead><tr><th>#</th><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>${rows(q).map((r,i)=>`<tr><td>${i+1}</td><td>${r.descripcion||''}</td><td>${r.cantidad||1}</td><td>${money(r.precio)}</td><td>${money((+r.cantidad||1)*(+r.precio||0))}</td></tr>`).join('')}</tbody></table><p class="total">Total: ${money(q.total)}</p><div class="firmas"><div class="line">Responsable técnico</div><div class="line">Área usuaria / conformidad</div></div></body></html>`}
function printHtml(html){let w=open('','_blank');w.document.write(html);w.document.close();w.print()} function exportCsv(el){let q=findQ(el); let csv=['descripcion,cantidad,precio,subtotal',...rows(q).map(r=>`"${r.descripcion}",${r.cantidad||1},${r.precio||0},${(+r.cantidad||1)*(+r.precio||0)}`)].join('\n');download(q.numero+'.csv',csv,'text/csv')} function exportWord(el){let q=findQ(el);download(q.numero+'.doc',docHtml(q,'COTIZACIÓN'),'application/msword')} function download(name,content,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click()}
function viewEjecucion(){return `<section class="wrap">${backBtn()}<h2>Ejecución</h2><select id="execQ">${state.cotizaciones.map(q=>`<option value="${q.id}">${q.numero} - ${q.clienteNombre}</option>`)}</select><p class="notice">Cada actividad/repuesto permite estado, observación y evidencia fotográfica.</p>${state.cotizaciones[0]?`<table class="table"><thead><tr><th>Actividad/Repuesto</th><th>Estado</th><th>Observación</th><th>Evidencia</th></tr></thead><tbody>${rows(state.cotizaciones[0]).map(r=>`<tr><td>${r.descripcion}</td><td><select><option>Pendiente</option><option>En proceso</option><option>Conforme</option><option>Observado</option></select></td><td><textarea placeholder="Observación técnica"></textarea></td><td><input type="file" accept="image/*"></td></tr>`).join('')}</tbody></table>`:''}</section>`}
function viewDocs(type){return `<section class="wrap">${backBtn()}<h2>${type==='acta'?'Actas':'Informes técnicos'}</h2>${state.cotizaciones.map(q=>`<div class="card"><b>${q.numero}</b> · ${q.clienteNombre} · ${money(q.total)}<br><button class="btn green" data-action="printDoc" data-id="${q.id}" data-type="${type}">Generar ${type}</button></div>`).join('')}</section>`}
function viewInventario(){return `<section class="wrap">${backBtn()}<h2>Inventario / QR / Código de barras</h2><div class="grid"><select id="invTipo"><option>Equipo</option><option>Repuesto</option><option>Accesorio</option></select><input id="invCod" placeholder="Código"><input id="invDesc" placeholder="Descripción"><input id="invSerie" placeholder="Serie"></div><br><button class="btn green" data-action="saveInv">Agregar</button><table class="table"><thead><tr><th>Tipo</th><th>Descripción</th><th>Código</th><th>QR</th><th>Barras</th></tr></thead><tbody>${state.inventario.map(i=>`<tr><td>${i.tipo}</td><td>${i.descripcion}</td><td>${i.codigo}</td><td>▣ ${i.codigo||i.id}</td><td>|||| ${i.codigo||i.id} ||||</td></tr>`).join('')}</tbody></table></section>`}
function saveInv(){let d=$('#invDesc').value.trim(); if(!d)return; state.inventario.push({id:uid(),tipo:$('#invTipo').value,codigo:$('#invCod').value,descripcion:d,serie:$('#invSerie').value});persist();render()}
function viewConfig(){return `<section class="wrap">${backBtn()}<h2>Configuración</h2><p class="notice">Estado: ${cloud}</p><p>Variables Vercel: VITE_SUPABASE_URL y VITE_SUPABASE_KEY.</p></section>`}
loadCloud(); render();
